name: Setup Node and npm
description: Setup Node.js, configure npm, and install dependencies

inputs:
  node-version:
    required: true
    description: Node.js version

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - run: npm config set fund false
      shell: bash

    - run: npm config set audit false
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash
